volumes:
  db_data:

services:
  db:
    image: postgres:17
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    ports:
      - "${SPRING_DATASOURCE_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ./backend
    container_name: askmate_app
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DATABASE_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      askMate.app.jwtSecret: ${JWT_SECRET}
      askMate.app.jwtExpirationMs: ${JWT_EXPIRATION_MS}
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend 
    container_name: askmate_frontend
    ports:
      - "3000:80"
    depends_on:
      - app