volumes:
  db_data:

services:
  database:
    image: postgres:18
    container_name: askmate_database
    restart: on-failure
    env_file:
      - .env
    environment:
      POSTGRES_DB: askmate
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME:-dkisb}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  backend:
    build:
      context: ./backend
    container_name: askmate_backend
    restart: on-failure
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/askmate
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    container_name: askmate_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
