spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

askMate.app.jwtSecret=hj/Jievmnm929JpCU0Ow6VUGqpn1tc39YX1cIIwYI/wTu/lDm4p3+oTZBHWtdmL3
askMate.app.jwtExpirationMs=86400000